import test from 'node:test';
import assert from 'node:assert/strict';
import { CombatEngine } from '../src/core/combat.js';
import { createCard, resolvedCard, upgradeCard, copyCard } from '../src/core/card.js';
import { cards } from '../src/data/cards.js';
import { characterClasses } from '../src/data/characters.js';
import { clerkExtension } from '../src/characters/clerk.js';
import { COMBAT_EVENTS } from '../src/core/event-bus.js';
let serial = 0;
function make(ids = [], options = {}) {
  const engine = new CombatEngine({ character: { ...characterClasses.clerk, drawPerTurn: 0 }, cardDefinitions: cards, extension: clerkExtension, encounter: { name: 'test', enemies: ['director'] }, deck: [], hp: 500, maxHp: 500, seed: 'TEST', ...options });
  engine.state.hand = ids.map(id => createCard(id, `test-${serial++}`)); engine.state.energy = 100;
  engine.state.enemies[0].hp = engine.state.enemies[0].maxHp = 10000;
  return engine;
}
function eventCount(engine, event) { return engine.state.log.filter(e=>e.event===event).length; }
function fileAll(engine) { for(const c of [...engine.state.hand]) engine.act('workflow:add',{cardId:c.id,free:true}); }
test('draw, discard and deterministic reshuffle keep every instance exactly once',()=>{
  const e=make(['strike','defend','read']); const ids=e.state.hand.map(c=>c.id).sort();
  e.deck.endTurn(); assert.equal(e.state.hand.length,0); assert.equal(e.state.discard.length,3);
  e.deck.draw(2); assert.equal(e.state.hand.length,2); assert.equal(e.state.draw.length,1); assert.equal(e.state.discard.length,0);
  e.deck.draw(5); assert.deepEqual(e.state.hand.map(c=>c.id).sort(),ids); assert.equal(eventCount(e,'deck:shuffled'),1);
});
test('draw respects hand limit and does not destroy overflow',()=>{const e=make(Array(12).fill('defend'));e.state.draw=[createCard('strike','overflow')];e.deck.draw(3);assert.equal(e.state.draw.length,1);assert.equal(e.state.hand.length,12);});
test('Exhaust cards leave ordinary piles after playing',()=>{const e=make(['coffee']);e.play(e.state.hand[0].id);assert.equal(e.state.exhaust.length,1);assert.equal(e.state.discard.length,0);assert.equal(eventCount(e,'card:exhausted'),1);});
test('Retain remains, Ethereal exhausts, ordinary cards discard',()=>{const e=make(['retain','haze','defend']);e.deck.endTurn();assert.equal(e.state.hand[0].definitionId,'retain');assert.equal(e.state.exhaust[0].definitionId,'haze');assert.equal(e.state.discard[0].definitionId,'defend');});
test('Ethereal takes precedence over Retain',()=>{const e=make(['retain']);e.state.hand[0].isCopy=true;e.deck.endTurn();assert.equal(e.state.hand.length,0);assert.equal(e.state.exhaust.length,1);});
test('Power leaves deck and keeps event-driven effect active throughout combat',()=>{const e=make(['power']);e.play(e.state.hand[0].id);assert.equal(e.state.powers.length,1);assert.equal(e.state.discard.length,0);e.startTurn();assert.equal(e.state.player.block,2);e.startTurn();assert.equal(e.state.player.block,2);});
test('upgrading changes final card effects and cost without changing definition',()=>{const c=createCard('strike','u');upgradeCard(c);assert.equal(resolvedCard(c,cards).effects[0].amount,9);assert.equal(cards.strike.effects[0].amount,6);const copy=createCard('copy','u2');upgradeCard(copy);assert.equal(resolvedCard(copy,cards).cost,0);});
test('annotations stack composable effects, cost, keywords and adjustments on one instance',()=>{
  const e=make(['strike','strike']);const c=e.state.hand[0];
  e.effects.execute([{type:'annotate',modifier:{label:'one',costDelta:-1,effects:[{type:'block',amount:3}],keywords:['Retain']}},{type:'annotate',modifier:{label:'two',effects:[{type:'draw',amount:1}],effectAdjustments:[{type:'damage',amountDelta:2}]}}],{cardId:c.id});
  const r=e.resolve(c);assert.equal(r.cost,0);assert.equal(r.effects[0].amount,8);assert.deepEqual(r.effects.map(e=>e.type),['damage','block','draw']);assert.deepEqual(r.keywords,['Retain']);assert.equal(e.state.hand[1].annotations.length,0);assert.equal(eventCount(e,'annotation:added'),2);
});
test('copy keeps upgrades and annotations, excludes noncopyable modifiers and has independent deep state',()=>{
  const source=createCard('strike','original',{upgrade:1,annotations:[{label:'red',effects:[{type:'block',amount:3}]}],modifiers:[{label:'yes',copyable:true,costDelta:-1},{label:'no',copyable:false,costDelta:1}]});
  const clone=copyCard(source,'clone');assert.equal(clone.upgrade,1);assert.equal(clone.annotations.length,1);assert.equal(clone.modifiers.length,1);assert.equal(clone.sourceId,'original');assert.equal(clone.rootSourceId,'original');assert.ok(resolvedCard(clone,cards).keywords.includes('Ethereal'));clone.annotations[0].effects[0].amount=999;assert.equal(source.annotations[0].effects[0].amount,3);
});
test('copy of a copy remains allowed and traces immediate and original sources',()=>{const a=createCard('defend','a');const b=copyCard(a,'b'),c=copyCard(b,'c'),d=copyCard(c,'d');assert.equal(d.sourceId,'c');assert.equal(d.rootSourceId,'a');assert.equal(d.isCopy,true);});
test('played copies return to discard and retain Ethereal after re-draw',()=>{const e=make(['defend']);const copy=copyCard(e.state.hand[0],'copied');e.state.hand=[copy];e.play(copy.id);assert.equal(e.state.discard[0].id,copy.id);assert.equal(e.state.exhaust.length,0);e.deck.draw(1);assert.equal(e.state.hand[0].isCopy,true);e.deck.endTurn();assert.equal(e.state.exhaust[0].id,copy.id);});
test('copy effect emits dedicated events and unplayed copies exhaust',()=>{const e=make(['copy','defend']);const source=e.state.hand[1];e.play(e.state.hand[0].id,{cardId:source.id});assert.equal(eventCount(e,'card:copied'),1);e.deck.endTurn();assert.equal(e.state.exhaust.length,1);assert.equal(e.state.discard.length,2);});
test('target selection rejects missing, dead and self targets without spending energy',()=>{const e=make(['strike','annotate']);const energy=e.state.energy;assert.throws(()=>e.play(e.state.hand[0].id));assert.throws(()=>e.play(e.state.hand[1].id,{cardId:e.state.hand[1].id}));assert.equal(e.state.energy,energy);assert.equal(e.state.hand.length,2);});
test('added damage effect introduces enemy target requirement for formerly untargeted skill',()=>{const e=make(['defend']);const c=e.state.hand[0];c.annotations.push({label:'attack',effects:[{type:'damage',amount:3,target:'enemy'}]});assert.throws(()=>e.play(c.id));e.play(c.id,{enemyId:e.state.enemies[0].id});assert.equal(e.state.player.block,5);assert.equal(e.state.enemies[0].hp,9997);});
test('cards with AutoWorkflow pay their cost and pack without immediate effects or ordinary play events',()=>{const e=make(['defend','defend','defend']);for(const card of [...e.state.hand]){card.modifiers.push({keywords:['AutoWorkflow']});e.play(card.id);}assert.equal(e.state.energy,97);assert.equal(e.state.player.block,0);assert.equal(eventCount(e,'card:played'),0);assert.equal(eventCount(e,'workflow:packed'),1);assert.equal(e.state.extensions.clerk.pending.length,0);assert.equal(e.state.extensions.clerk.workflows[0].items.length,3);assert.equal(e.state.discard.length,0);});
test('workflow cycles 1→2→3→1 without fees, ordinary plays or removing Exhaust/Ethereal items',()=>{
  const e=make(['defend','retain','haze']);const ids=e.state.hand.map(c=>c.id);fileAll(e);
  for(let i=0;i<4;i++) e.startTurn();
  const events=e.state.log.filter(e=>e.event==='workflow:item-executed');assert.deepEqual(events.map(e=>e.index),[0,1,2,0]);assert.deepEqual(events.map(e=>e.cardId),[...ids,ids[0]]);assert.equal(eventCount(e,'card:played'),0);assert.equal(e.state.extensions.clerk.workflows[0].items.length,3);assert.equal(e.state.energy,3);assert.equal(e.state.exhaust.length,0);
});
test('multiple simultaneous workflows advance independently with no fixed limit',()=>{
  const e=make(Array(18).fill('defend'));fileAll(e);assert.equal(e.state.extensions.clerk.workflows.length,6);e.startTurn();assert.equal(e.state.player.block,30);assert.ok(e.state.extensions.clerk.workflows.every(f=>f.cursor===1));
  e.state.hand.push(...['defend','defend','defend'].map((id,i)=>createCard(id,`later${i}`)));fileAll(e);e.startTurn();assert.equal(e.state.player.block,35);assert.equal(e.state.extensions.clerk.workflows[0].cursor,2);assert.equal(e.state.extensions.clerk.workflows[6].cursor,1);
});
test('workflow stores upgraded annotated copy state and its keywords do not remove it',()=>{const e=make(['strike','defend','coffee']);const card=e.state.hand[0];upgradeCard(card);card.isCopy=true;card.annotations=[{label:'red',effects:[{type:'damage',amount:4,target:'enemy'}]}];fileAll(e);e.startTurn();assert.equal(e.state.enemies[0].hp,9987);assert.equal(e.state.extensions.clerk.workflows[0].items[0].annotations.length,1);e.startTurn();e.startTurn();assert.equal(e.state.extensions.clerk.workflows[0].items.length,3);assert.equal(e.state.energy,5);});
test('workflow lethal effect ends combat and does not act as player play',()=>{const e=make(['strike','defend','defend']);fileAll(e);e.state.enemies[0].hp=5;e.startTurn();assert.equal(e.state.outcome,'victory');assert.equal(eventCount(e,'workflow:item-executed'),1);assert.equal(eventCount(e,'card:played'),0);assert.equal(eventCount(e,'combat:end'),1);});
test('workflow power listeners and relics respond via event bus',()=>{const e=make(['auto','defend','defend','defend'],{relics:['binder']});e.play(e.state.hand[0].id);fileAll(e);assert.equal(e.state.energy,100);e.startTurn();assert.equal(e.state.player.block,7);});
test('relic annotation and copy listeners are triggered',()=>{const e=make(['defend'],{relics:['redPen','carbonPaper']});e.effects.execute([{type:'annotate',modifier:{label:'test',effects:[]}},{type:'copy',amount:2}],{cardId:e.state.hand[0].id});assert.equal(e.state.player.block,6);});
test('all enemy intents execute, block absorbs damage, status damage modifies attacks',()=>{const e=make(['defend'],{encounter:{enemies:['queue','paper']}});e.state.player.block=4;const hp=e.state.player.hp;e.endTurn();assert.equal(e.state.player.hp,hp-7);assert.equal(e.state.turn,2);assert.equal(e.state.player.block,0);e.state.player.statuses={strength:2,weak:1};e.state.hand=[createCard('strike','s')];e.play('s',{enemyId:e.state.enemies[0].id});assert.equal(e.state.enemies[0].hp,9994);});
test('defeat ends combat once and halts subsequent enemy actions',()=>{const e=make([],{encounter:{enemies:['queue','queue']}});e.state.player.hp=1;e.endTurn();assert.equal(e.state.outcome,'defeat');assert.equal(e.state.player.hp,0);assert.equal(e.state.turn,1);assert.equal(eventCount(e,'combat:end'),1);});
test('generic combat works with another class without clerk extensions or draw/energy assumptions',()=>{const e=make([],{character:{id:'other',energyPerTurn:7,drawPerTurn:()=>1},extension:null});e.state.draw=[createCard('defend','other')];assert.deepEqual(e.state.extensions,{});e.startTurn();assert.equal(e.state.energy,7);assert.equal(e.state.hand.length,1);assert.equal(e.actions.size,0);});
test('all specified event types are part of unified bus contract',()=>{for(const name of ['turn:start','turn:end','card:drawn','card:played','card:exhausted','card:copied','annotation:added','damage:dealt','damage:taken','block:gained','energy:spent','workflow:packed','workflow:item-executed','combat:start','combat:end'])assert.ok(COMBAT_EVENTS.includes(name));});
test('verbose logs can be turned off without disabling mechanics',()=>{const e=make(['defend']);e.state.logEnabled=false;const before=e.state.log.length;e.play(e.state.hand[0].id);assert.equal(e.state.player.block,5);assert.equal(e.state.log.length,before);});
test('copy effect recursively copies copies and emits one event per generation',()=>{const e=make(['defend']);let source=e.state.hand[0];source.annotations=[{label:'nested',effects:[{type:'draw',amount:1}]}];const root=source.id;for(let i=0;i<5;i++){e.effects.execute([{type:'copy',amount:1}],{cardId:source.id});const result=e.state.hand.at(-1);assert.equal(result.sourceId,source.id);assert.equal(result.rootSourceId,root);assert.deepEqual(result.annotations,source.annotations);source=result;}assert.equal(eventCount(e,'card:copied'),5);});
test('workflows packed during a turn-start execution wait until the next turn',()=>{const e=make(['file','defend','defend']);fileAll(e);e.state.hand=['strike','strike','defend'].map((id,i)=>createCard(id,`packing-${i}`));for(let i=0;i<2;i++)e.act('workflow:add',{cardId:e.state.hand[0].id,free:true});e.startTurn();assert.equal(e.state.extensions.clerk.workflows.length,2);assert.equal(e.state.extensions.clerk.workflows[1].cursor,0);assert.equal(e.state.extensions.clerk.workflows[1].executions,0);e.startTurn();assert.equal(e.state.extensions.clerk.workflows[1].executions,1);});
test('status event listeners modify outgoing attack calculations and decay on lifecycle events',()=>{const e=make(['strike']);e.state.player.statuses={weak:2,strength:2};e.play(e.state.hand[0].id,{enemyId:e.state.enemies[0].id});assert.equal(e.state.enemies[0].hp,9994);assert.equal(eventCount(e,'attack:calculate'),1);e.endTurn();assert.equal(e.state.player.statuses.weak,1);assert.equal(e.state.player.statuses.strength,2);});
test('a targeted card does not silently redirect its remaining annotations after killing that target',()=>{const e=make(['strike'],{encounter:{enemies:['paper','paper']}});e.state.enemies[0].hp=5;e.state.hand[0].annotations=[{label:'extra',effects:[{type:'damage',amount:3,target:'enemy'}]}];e.play(e.state.hand[0].id,{enemyId:e.state.enemies[0].id});assert.equal(e.state.enemies[0].hp,0);assert.equal(e.state.enemies[1].hp,22);});
